version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    # Removido o volume daqui, pois o Hub não executa navegadores
    environment:
      - GRID_MAX_SESSION=4
      - GRID_TIMEOUT=60
      - GRID_ADMIN_USER=${SELENIUM_HUB_USER}
      - GRID_ADMIN_PASSWORD=${SELENIUM_HUB_PASSWORD}
    networks:
      - selenium-network

  chrome:
    image: selenium/node-chrome:latest
    container_name: selenium-node-chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    ports:
      - "7900:7900"  
    # ADICIONADO AQUI: O nó de execução é quem precisa persistir o perfil do Chrome
    volumes:
      - ./chrome-profile:/home/seluser/chrome-profile 
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_SESSION=2
      - GRID_ADMIN_USER=${SELENIUM_HUB_USER}
      - GRID_ADMIN_PASSWORD=${SELENIUM_HUB_PASSWORD}
      - VNC_PASSWORD=${SELENIUM_VNC_PASSWORD}
    networks:
      - selenium-network

networks:
  selenium-network:
    driver: bridge

